name: Continuous Deployment

on:
  push:
    branches:
      - master  # Trigger on pushes to the main branch
  pull_request:
    branches:
      - master  # Trigger on pull requests targeting the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: integration-tests  # Dependency on integration tests job from ci.yml

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Deploy to production
        run: |
          echo "Deploying to production..."
          # Add your deployment scripts or commands here
