name: CD

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: integration-tests

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Check if package.json has changed
        id: package-check
        run: |
          echo "::set-output name=modified::$(git diff --name-only HEAD^ HEAD | grep package.json)"
      
      - name: Install dependencies and build
        if: steps.package-check.outputs.modified
        run: |
          npm install --production  # Install only production dependencies
          npm run build  # Replace with your build command if applicable

      - name: Transfer files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}  # Use password for SSH authentication
          source: '.'  # Path to your application code
          target: '/path/to/deploy'  # Destination directory on server

      - name: Restart PM2 for Node.js application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}  # Use password for SSH authentication
          script: |
            cd /path/to/deploy
            pm2 reload app.js --name "your-app-name"
