name: CI

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
        continue-on-error: true  # Continue on test failures

      - name: Set test status output
        id: set-test-status
        run: echo "::set-output name=tests-passed::$(if [ $? -eq 0 ]; then echo 'true'; else echo 'false'; fi)"
